name: packaging and delivery 

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
#       - name: Clone the Pipeline repo
#         run: git clone https://github.com/bdb-khetan-pawar/test1.git

#       - name: moved file from current location to targeted location
#         run: ls 

#       - name: Clone the Dashboard repo
#         run: git clone https://github.com/bdb-khetan-pawar/test2.git 

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          username: jackpawar
          password: 7805869992

      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jackpawar/newtest:latest
